controllers:
    resource: ../src/Controller/
    type: attribute

# redirecting the homepage
login:
    path: /
    controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController::urlRedirectAction
    defaults:
        path: /login
        permanent: true
